# Generated by Django 5.0.2 on 2024-02-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('name_of_degree', models.CharField(max_length=50)),
                ('admission_session', models.IntegerField()),
                ('reg_no', models.IntegerField()),
                ('batch', models.IntegerField()),
                ('graduating_session', models.IntegerField()),
                ('cgpa', models.FloatField()),
            ],
        ),
    ]
